xkb: Add missing header for libcxx-23
Starting with libcxx-23 transitive headers are being removed from their
C++ standard library.

error: no member named 'mbstowcs' in namespace 'std'

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>